---
- name: Install packages based on OS type
  hosts: all
  become: yes
  gather_facts: yes   # Make sure ansible_os_family is available

  tasks:
    - name: Install nginx on RedHat/CentOS
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install vim on all OS types
      ansible.builtin.package:
        name: vim
        state: present
      when: ansible_facts['os_family'] is defined
